


export const ZOOM_TO_SYSTEM = "ZOOM_TO_SYSTEM";
export const SEARCH_SYSTEMS_ON = "SEARCH_SYSTEMS_ON";
export const SEARCH_SYSTEMS_OFF = "SEARCH_SYSTEMS_OFF";
export const ZOOM_TO_SYSTEM_ERROR = 'ZOOM_TO_SYSTEM_ERROR';
export const GET_ZOOM_VALUE = 'GET_ZOOM_VALUE';
export const SET_ZOOM_VALUE = 'SET_ZOOM_VALUE';
export const MAP_RENDER_ON = 'MAP_RENDER_ON';
export const MAP_RENDER_OFF = 'MAP_RENDER_OFF';
export const MAP_RENDER_STATUS = 'MAP_RENDER_STATUS';



export const ZOOM_CHANGE_ON = 'ZOOM_CHANGE_ON';
export const ZOOM_CHANGE_OFF = 'ZOOM_CHANGE_OFF';
export const ZOOM_CHANGE_STATUS = 'ZOOM_CHANGE_STATUS';

