


export const ZOOM_TO_SYSTEM = "ZOOM_TO_SYSTEM";
export const SEARCH_SYSTEMS_ON = "SEARCH_SYSTEMS_ON";
export const SEARCH_SYSTEMS_OFF = "SEARCH_SYSTEMS_OFF";
export const ZOOM_TO_SYSTEM_ERROR = 'ZOOM_TO_SYSTEM_ERROR';
export const GET_ZOOM_VALUE = 'GET_ZOOM_VALUE';
export const SET_ZOOM_VALUE = 'SET_ZOOM_VALUE';


