


const UPDATE_SOUTH_WEST_MAP_HASH = "UPDATE_SOUTH_WEST_MAP_HASH";
const CLEAR_SOUTH_WEST_MAP_HASH = "CLEAR_SOUTH_WEST_MAP_HASH";

const UPDATE_NORTH_EAST_MAP_HASH = "UPDATE_NORTH_EAST_MAP_HASH";
const CLEAR_NORTH_EAST_MAP_HASH = "CLEAR_NORTH_EAST_MAP_HASH";



const ADD_DATA_STREAM_ITEM = "ADD_DATA_STREAM_ITEM";
const SET_CURRENT_DATA_STREAM_ITEM_TEMP = "SET_CURRENT_DATA_STREAM_ITEM_TEMP";
const SET_CURRENT_DATA_STREAM_ITEM_TO_MOST_RECENT = "SET_CURRENT_DATA_STREAM_ITEM_TO_MOST_RECENT";
const SET_CURRENT_DATA_STREAM_ITEM_TO_BLANK = "SET_CURRENT_DATA_STREAM_ITEM_TO_BLANK";
const DECODE_ADDITIONAL_LETTER = "DECODE_ADDITIONAL_LETTER";
const RE_ENCODE_PREVIOUS_LETTER = "RE_ENCODE_PREVIOUS_LETTER";
const ZERO_DECODE_LETTERS = "ZERO_DECODE_LETTERS";


const SYSTEMS_SEARCH_CONTROLS_ON = "SYSTEMS_SEARCH_CONTROLS_ON";
const SYSTEMS_SEARCH_CONTROLS_OFF = "SYSTEMS_SEARCH_CONTROLS_OFF";
const SYSTEMS_SEARCH_CONTROLS_TOGGLE = "SYSTEMS_SEARCH_CONTROLS_TOGGLE";


const MAP_CONTROLS_ON = "MAP_CONTROLS_ON";
const MAP_CONTROLS_OFF = "MAP_CONTROLS_OFF";
const MAP_CONTROLS_TOGGLE = "MAP_CONTROLS_TOGGLE";

const HYPERSPACE_NAVIGATION_CONTROLS_ON = "HYPERSPACE_NAVIGATION_CONTROLS_ON";
const HYPERSPACE_NAVIGATION_CONTROLS_OFF = "HYPERSPACE_NAVIGATION_CONTROLS_OFF";
const HYPERSPACE_NAVIGATION_CONTROLS_TOGGLE = "HYPERSPACE_NAVIGATION_CONTROLS_TOGGLE";

const SET_SYSTEM = "SET_SYSTEM";
const SET_SYSTEM_ERROR = "SET_SYSTEM_ERROR";
const SET_SYSTEM_TO_CORUSCANT = "SET_SYSTEM_TO_CORUSCANT";
const INCREMENT_SYSTEM_ZOOM = "INCREMENT_SYSTEM_ZOOM";
const DECREMENT_SYSTEM_ZOOM = "DECREMENT_SYSTEM_ZOOM";
const SET_SYSTEM_ZOOM_VALUE = "SET_SYSTEM_ZOOM_VALUE";

const SET_MAP_CENTER = "SET_MAP_CENTER";
const SET_MAP_ZOOM = "SET_MAP_ZOOM";
const SET_MAP_CENTER_AND_ZOOM = "SET_MAP_CENTER_AND_ZOOM";
const SET_MAP_CENTER_AND_ZOOM_TO_DEFAULT = "SET_MAP_CENTER_AND_ZOOM_TO_DEFAULT";
const SET_MAP_ERROR = "SET_MAP_ERROR";
const INCREASE_MAP_ZOOM_BY_ONE = "INCREASE_MAP_ZOOM_BY_ONE";
const DECREASE_MAP_ZOOM_BY_ONE = "DECREASE_MAP_ZOOM_BY_ONE";

const SEARCH_SYSTEMS_ON = "SEARCH_SYSTEMS_ON";
const SEARCH_SYSTEMS_OFF = "SEARCH_SYSTEMS_OFF";

const LOAD_HYPERSPACE_COLLECTION = 'LOAD_HYPERSPACE_COLLECTION';
const EMPTY_HYPERSPACE_COLLECTION = 'EMPTY_HYPERSPACE_COLLECTION';
const ADD_HYPERSPACE_COLLECTION = 'ADD_HYPERSPACE_COLLECTION';
const ERROR_HYPERSPACE_COLLECTION = 'ERROR_HYPERSPACE_COLLECTION';

const HYPERSPACE_PATH_CHANGE_ON = 'HYPERSPACE_PATH_CHANGE_ON';
const HYPERSPACE_PATH_CHANGE_OFF = 'HYPERSPACE_PATH_CHANGE_OFF';
const HYPERSPACE_PATH_CHANGE_STATUS = 'HYPERSPACE_PATH_CHANGE_STATUS';

const PATH_SEARCH_ON = 'PATH_SEARCH_ON';
const PATH_SEARCH_OFF = 'PATH_SEARCH_OFF';

const PATH_SEARCH_START_ON = 'PATH_SEARCH_START_ON';
const PATH_SEARCH_START_OFF = 'PATH_SEARCH_START_OFF';

const PATH_SEARCH_END_ON = 'PATH_SEARCH_END_ON';
const PATH_SEARCH_END_OFF = 'PATH_SEARCH_END_OFF';

const SET_START_POSITION = 'SET_START_POSITION';
const SET_START_POSITION_ERROR = 'SET_START_POSITION_ERROR';
const SET_END_POSITION = 'SET_END_POSITION';
const SET_END_POSITION_ERROR = 'SET_END_POSITION_ERROR';

const SET_START_NODE = 'SET_START_NODE';
const SET_START_NODE_ERROR = 'SET_START_NODE_ERROR';
const SET_END_NODE = 'SET_END_NODE';
const SET_END_NODE_ERROR = 'SET_END_NODE_ERROR';

const CALCULATE_HYPERSPACE_JUMP_ON = 'CALCULATE_HYPERSPACE_JUMP_ON';
const CALCULATE_HYPERSPACE_JUMP_OFF = 'CALCULATE_HYPERSPACE_JUMP_OFF';

const PIN_POINT_START_ON = 'PIN_POINT_START_ON';
const PIN_POINT_START_OFF = 'PIN_POINT_START_OFF';
const PIN_POINT_START_TOGGLE = 'PIN_POINT_START_TOGGLE';

const PIN_POINT_END_ON = 'PIN_POINT_END_ON';
const PIN_POINT_END_OFF = 'PIN_POINT_END_OFF';
const PIN_POINT_END_TOGGLE = 'PIN_POINT_END_TOGGLE';

const SET_START_SYSTEM = 'SET_START_SYSTEM';
const SET_START_SYSTEM_ERROR = 'SET_START_SYSTEM_ERROR';
const SET_START_SYSTEM_EMPTY = 'SET_START_SYSTEM_EMPTY';

const SET_END_SYSTEM = 'SET_END_SYSTEM';
const SET_END_SYSTEM_ERROR = 'SET_END_SYSTEM_ERROR';
const SET_END_SYSTEM_EMPTY = 'SET_END_SYSTEM_EMPTY';

const SET_MAX_JUMPS = 'SET_MAX_JUMPS';
const SET_MAX_JUMPS_ERROR = 'SET_MAX_JUMPS_ERROR';

const GENERATE_MAP_HASH = 'GENERATE_MAP_HASH';
const DEFAULT_MAP_HASH = 'DEFAULT_MAP_HASH';
const SAME_MAP_HASH = 'SAME_MAP_HASH';

const UPDATE_HYPERSPACE_NAVIGATION_ON = 'UPDATE_HYPERSPACE_NAVIGATION_ON';
const UPDATE_HYPERSPACE_NAVIGATION_OFF = 'UPDATE_HYPERSPACE_NAVIGATION_OFF';


const SET_ACTVIE_START_POSITION = 'SET_ACTVIE_START_POSITION';
const SET_ACTVIE_START_POSITION_DEFAULT = 'SET_ACTVIE_START_POSITION_DEFAULT';

const SET_ACTVIE_END_POSITION = 'SET_ACTVIE_END_POSITION';
const SET_ACTVIE_END_POSITION_DEFAULT = 'SET_ACTVIE_END_POSITION_DEFAULT';

const HYPERSPACE_POINT_ZOOM_ON = 'HYPERSPACE_POINT_ZOOM_ON';
const HYPERSPACE_POINT_ZOOM_OFF = 'HYPERSPACE_POINT_ZOOM_OFF';

const SET_ACTVIE_START_NODE = 'SET_ACTVIE_START_NODE';
const SET_ACTVIE_START_NODE_DEFAULT = 'SET_ACTVIE_START_NODE_DEFAULT';

const SET_ACTVIE_END_NODE = 'SET_ACTVIE_END_NODE';
const SET_ACTVIE_END_NODE_DEFAULT = 'SET_ACTVIE_END_NODE_DEFAULT';

const Actions = {
	SET_ACTVIE_START_NODE: 'SET_ACTVIE_START_NODE',
	SET_ACTVIE_START_NODE_DEFAULT: 'SET_ACTVIE_START_NODE_DEFAULT',

	SET_ACTVIE_END_NODE: 'SET_ACTVIE_END_NODE',
	SET_ACTVIE_END_NODE_DEFAULT: 'SET_ACTVIE_END_NODE_DEFAULT',

	HYPERSPACE_POINT_ZOOM_ON: "HYPERSPACE_POINT_ZOOM_ON",
	HYPERSPACE_POINT_ZOOM_OFF: "HYPERSPACE_POINT_ZOOM_OFF",
	
	SET_ACTVIE_START_POSITION: "SET_ACTVIE_START_POSITION",
	SET_ACTVIE_START_POSITION_DEFAULT: "SET_ACTVIE_START_POSITION_DEFAULT",

	SET_ACTVIE_END_POSITION: "SET_ACTVIE_END_POSITION",
	SET_ACTVIE_END_POSITION_DEFAULT: "SET_ACTVIE_END_POSITION_DEFAULT",
	
	SET_ACTIVE_HYPERSPACE_JUMP: "SET_ACTIVE_HYPERSPACE_JUMP",
	SET_NULL_ACTIVE_HYPERSPACE_JUMP: "SET_NULL_ACTIVE_HYPERSPACE_JUMP",

	SET_SELECTED_HYPERSPACE_HASH: "SET_SELECTED_HYPERSPACE_HASH",
	SET_NULL_HYPERSPACE_HASH: "SET_NULL_HYPERSPACE_HASH",


	UPDATE_NORTH_EAST_MAP_HASH: "UPDATE_NORTH_EAST_MAP_HASH",
	UPDATE_SOUTH_WEST_MAP_HASH: "UPDATE_SOUTH_WEST_MAP_HASH",
	CLEAR_NORTH_EAST_MAP_HASH: "CLEAR_NORTH_EAST_MAP_HASH",
	CLEAR_SOUTH_WEST_MAP_HASH: "CLEAR_SOUTH_WEST_MAP_HASH",


	ADD_DATA_STREAM_ITEM : "ADD_DATA_STREAM_ITEM",
	SET_CURRENT_DATA_STREAM_ITEM_TEMP : "SET_CURRENT_DATA_STREAM_ITEM_TEMP",
	SET_CURRENT_DATA_STREAM_ITEM_TO_MOST_RECENT : "SET_CURRENT_DATA_STREAM_ITEM_TO_MOST_RECENT",
	SET_CURRENT_DATA_STREAM_ITEM_TO_BLANK : "SET_CURRENT_DATA_STREAM_ITEM_TO_BLANK",
	DECODE_ADDITIONAL_LETTER : "DECODE_ADDITIONAL_LETTER",
	RE_ENCODE_PREVIOUS_LETTER : "RE_ENCODE_PREVIOUS_LETTER",
	ZERO_DECODE_LETTERS : "ZERO_DECODE_LETTERS",


	SYSTEMS_SEARCH_CONTROLS_ON : "SYSTEMS_SEARCH_CONTROLS_ON",
	SYSTEMS_SEARCH_CONTROLS_OFF : "SYSTEMS_SEARCH_CONTROLS_OFF",
	SYSTEMS_SEARCH_CONTROLS_TOGGLE : "SYSTEMS_SEARCH_CONTROLS_TOGGLE",


	MAP_CONTROLS_ON : "MAP_CONTROLS_ON",
	MAP_CONTROLS_OFF : "MAP_CONTROLS_OFF",
	MAP_CONTROLS_TOGGLE : "MAP_CONTROLS_TOGGLE",

	HYPERSPACE_NAVIGATION_CONTROLS_ON : "HYPERSPACE_NAVIGATION_CONTROLS_ON",
	HYPERSPACE_NAVIGATION_CONTROLS_OFF : "HYPERSPACE_NAVIGATION_CONTROLS_OFF",
	HYPERSPACE_NAVIGATION_CONTROLS_TOGGLE : "HYPERSPACE_NAVIGATION_CONTROLS_TOGGLE",

	SET_SYSTEM : "SET_SYSTEM",
	SET_SYSTEM_ERROR : "SET_SYSTEM_ERROR",
	SET_SYSTEM_TO_CORUSCANT : "SET_SYSTEM_TO_CORUSCANT",
	INCREMENT_SYSTEM_ZOOM : "INCREMENT_SYSTEM_ZOOM",
	DECREMENT_SYSTEM_ZOOM : "DECREMENT_SYSTEM_ZOOM",
	SET_SYSTEM_ZOOM_VALUE : "SET_SYSTEM_ZOOM_VALUE",

	SET_MAP_CENTER : "SET_MAP_CENTER",
	SET_MAP_ZOOM : "SET_MAP_ZOOM",
	SET_MAP_CENTER_AND_ZOOM : "SET_MAP_CENTER_AND_ZOOM",
	SET_MAP_CENTER_AND_ZOOM_TO_DEFAULT : "SET_MAP_CENTER_AND_ZOOM_TO_DEFAULT",
	SET_MAP_ERROR : "SET_MAP_ERROR",
	INCREASE_MAP_ZOOM_BY_ONE : "INCREASE_MAP_ZOOM_BY_ONE",
	DECREASE_MAP_ZOOM_BY_ONE : "DECREASE_MAP_ZOOM_BY_ONE",

	SEARCH_SYSTEMS_ON : "SEARCH_SYSTEMS_ON",
	SEARCH_SYSTEMS_OFF : "SEARCH_SYSTEMS_OFF",

	LOAD_HYPERSPACE_COLLECTION : 'LOAD_HYPERSPACE_COLLECTION',
	EMPTY_HYPERSPACE_COLLECTION : 'EMPTY_HYPERSPACE_COLLECTION',
	ADD_HYPERSPACE_COLLECTION : 'ADD_HYPERSPACE_COLLECTION',
	ERROR_HYPERSPACE_COLLECTION : 'ERROR_HYPERSPACE_COLLECTION',

	HYPERSPACE_PATH_CHANGE_ON : 'HYPERSPACE_PATH_CHANGE_ON',
	HYPERSPACE_PATH_CHANGE_OFF : 'HYPERSPACE_PATH_CHANGE_OFF',
	HYPERSPACE_PATH_CHANGE_STATUS : 'HYPERSPACE_PATH_CHANGE_STATUS',

	PATH_SEARCH_ON : 'PATH_SEARCH_ON',
	PATH_SEARCH_OFF : 'PATH_SEARCH_OFF',

	PATH_SEARCH_START_ON : 'PATH_SEARCH_START_ON',
	PATH_SEARCH_START_OFF : 'PATH_SEARCH_START_OFF',

	PATH_SEARCH_END_ON : 'PATH_SEARCH_END_ON',
	PATH_SEARCH_END_OFF : 'PATH_SEARCH_END_OFF',

	SET_START_POSITION : 'SET_START_POSITION',
	SET_START_POSITION_ERROR : 'SET_START_POSITION_ERROR',
	SET_END_POSITION : 'SET_END_POSITION',
	SET_END_POSITION_ERROR : 'SET_END_POSITION_ERROR',

	SET_START_NODE : 'SET_START_NODE',
	SET_START_NODE_ERROR : 'SET_START_NODE_ERROR',
	SET_END_NODE : 'SET_END_NODE',
	SET_END_NODE_ERROR : 'SET_END_NODE_ERROR',

	CALCULATE_HYPERSPACE_JUMP_ON : 'CALCULATE_HYPERSPACE_JUMP_ON',
	CALCULATE_HYPERSPACE_JUMP_OFF : 'CALCULATE_HYPERSPACE_JUMP_OFF',

	PIN_POINT_START_ON : 'PIN_POINT_START_ON',
	PIN_POINT_START_OFF : 'PIN_POINT_START_OFF',
	PIN_POINT_START_TOGGLE : 'PIN_POINT_START_TOGGLE',

	PIN_POINT_END_ON : 'PIN_POINT_END_ON',
	PIN_POINT_END_OFF : 'PIN_POINT_END_OFF',
	PIN_POINT_END_TOGGLE : 'PIN_POINT_END_TOGGLE',

	SET_START_SYSTEM : 'SET_START_SYSTEM',
	SET_START_SYSTEM_ERROR : 'SET_START_SYSTEM_ERROR',
	SET_START_SYSTEM_EMPTY : 'SET_START_SYSTEM_EMPTY',

	SET_END_SYSTEM : 'SET_END_SYSTEM',
	SET_END_SYSTEM_ERROR : 'SET_END_SYSTEM_ERROR',
	SET_END_SYSTEM_EMPTY : 'SET_END_SYSTEM_EMPTY',

	SET_MAX_JUMPS : 'SET_MAX_JUMPS',
	SET_MAX_JUMPS_ERROR : 'SET_MAX_JUMPS_ERROR',

	GENERATE_MAP_HASH : 'GENERATE_MAP_HASH',
	DEFAULT_MAP_HASH : 'DEFAULT_MAP_HASH',
	SAME_MAP_HASH : 'SAME_MAP_HASH',

	UPDATE_HYPERSPACE_NAVIGATION_ON : 'UPDATE_HYPERSPACE_NAVIGATION_ON',
	UPDATE_HYPERSPACE_NAVIGATION_OFF : 'UPDATE_HYPERSPACE_NAVIGATION_OFF',


};

export default Actions;

